# Some general purpose variables
user_home_directory: /home/myuser
user: myuser

# Golang related setup
go:
  enabled: false
  bin_path: /home/myuser/go/bin
  version: 1.19.2
  env: # Define environment variables used by go
    gonoproxy: null
    gonosumdb: null
    goproxy: null
  install: # Go packages to install
    - github.com/google/pprof@latest
    - golang.org/x/vuln/cmd/govulncheck@latest
    - github.com/golangci/golangci-lint/cmd/golangci-lint@latest

# Yubikey setup
yubikey:
  enabled: false

# Wireguard setup
wireguard:
  enabled: false
  alias_vpn_name: "My VPN" # vpn-up and vpn-down aliases will be created for this vpn

# Rust setup
rust:
  enabled: false

# Git setup
git:
  enabled: false
  email: name@example.com
  name: username
  # GPG key used for signing: "gpg --list-secret-keys --keyid-format LONG"
  # Line with [S] the part after "rsaXXXX/"
  signingkey: abcde
  # Enables commit signing globally. Not required if signingkey set.
  enableGlobalSigning: false

# Gnome settings
gnome:
  enabled: false
  wallpaper: https://example.com/mypic.jpg

# Packages to install
packages:
  enabled: false
  apt:
    - keepassxc
  snap:
    - firefox
  # Snap packages requiring --classic flag
  snap_classic:
    - code

# OpenSnitch network firewall
opensnitch:
  enabled: false
  version: 1.6.0-rc.4

# Docker settings
docker:
  enabled: false

# Teamspeak settings
# Requres manual steps, you will be prompted by ansible
ts:
  enabled: false
  version: "3.5.6"

# Flutter settings
flutter:
  enabled: false

# Grub settings
grub:
  enabled: false
  hide_bootmenu: true

# Darktable settings
darktable:
  enabled: false
  version: 4.8.1

# Seafile settings
seafile:
  enabled: false

# KeepassXC settings
keepassxc:
  enabled: false

# FreeCAD settings
freecad:
  enabled: false
  #Currently hardcoded to v1.0rc2
  version: v1.0rc2

# CCC hub settings
ccc_hub: 
  enabled: false

# gLabels settings
glabels: 
  enabled: false