# Some general purpose variables
user_home_directory: /home/myuser
user: myuser

# Golang related setup
go:
  enabled: false
  bin_path: /home/myuser/go/bin
  version: 1.19.2
  env: # Define environment variables used by go
    gonoproxy: null
    gonosumdb: null
    goproxy: null

# Yubikey setup
yubikey:
  enabled: false

# Wireguard setup
wireguard:
  enabled: false
  alias_vpn_name: "My VPN" # vpn-up and vpn-down aliases will be created for this vpn

# Rust setup
rust:
  enabled: false

# Git setup
git:
  enabled: false
  email: name@example.com
  name: username

# Gnome settings
gnome:
  enabled: false
  wallpaper: https://example.com/mypic.jpg