- name: Install dependencies
  apt:
    pkg:
      - nano
    state: latest
    update_cache: true
  become: true
- name: Update .bashrc to include .bashrc_workstation
  lineinfile:
    dest: "{{ user_home_directory }}/.bashrc"
    line: "[ -f $HOME/.bashrc_workstation ] && . $HOME/.bashrc_workstation"
- name: Search directories
  find:
    path: ./roles/dotfiles/templates
    file_type: directory
    recurse: true
    hidden: true
  register: result
- name: Create directories
  file:
    state: directory
    path: "{{ user_home_directory }}/{{ _path }}"
  loop: "{{ result.files|map(attribute='path')|list }}"
  vars:
    _path: "{{ item | regex_replace('^roles/dotfiles/templates/', '') }}"
- name: Search files
  find:
    path: ./roles/dotfiles/templates
    recurse: true
    hidden: true
  register: result
- name: Create files
  template:
    src: "{{ _path }}.j2"
    dest: "{{ user_home_directory }}/{{ _path }}"
  loop: "{{ result.files|map(attribute='path')|list }}"
  vars:
    _path: "{{ item | regex_replace('^roles/dotfiles/templates/', '') | regex_replace('\\.j2', '') }}"
