- name: Download Darktable
  get_url:
    url: "https://github.com/darktable-org/darktable/releases/download/release-{{ darktable.version }}/darktable-{{ darktable.version }}-x86_64.AppImage"   
    dest: "{{ user_home_directory }}/deb/darktable_{{ darktable.version }}.AppImage"
    mode: 0774
- name: Download Darktable Icon
  get_url:
    url: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Darktable_icon.svg"   
    dest: "{{ user_home_directory }}/deb/darktable.svg"
    mode: 0774