- name: Make tmp folder
  file:
    state: directory
    path: "/tmp/ansible/teamspeak"
- name: Make user folder
  file:
    path: "{{ user_home_directory }}/teamspeak"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775
- name: Download
  get_url:
    url: "https://files.teamspeak-services.com/releases/client/{{ ts.version }}/TeamSpeak3-Client-linux_amd64-{{ ts.version }}.run"
    dest: "/tmp/ansible/teamspeak"
    mode: 0760
- name: Manual install
  ansible.builtin.pause:
    prompt: "Please execute: sudo bash /tmp/ansible/teamspeak/TeamSpeak3-Client-linux_amd64-{{ ts.version }}.run"
- name: Download icon
  get_url:
    url: "https://repository-images.githubusercontent.com/245183073/ddc53200-6c90-11ea-9cd4-4420dd77ae00"
    dest: "{{ user_home_directory }}/TeamSpeak3-Client-linux_amd64/logo.png"
- name: Create desktop file
  template:
    src: "ts3-client.desktop.j2"
    dest: "{{ user_home_directory }}/.local/share/applications/teamspeak3-client.desktop"

# Cleanup
- name: Remove tmp folder
  file:
    state: absent
    path: "/tmp/ansible/teamspeak"