- name: Install apt packages
  apt:
    pkg:
      - libfuse2
    state: latest
    update_cache: true
- name: Download FreeCAD
  get_url:
    url: "https://github.com/FreeCAD/FreeCAD/releases/download/{{ freecad.version }}/FreeCAD-{{ freecad.version }}-Linux-x86_64.AppImage"   
    dest: "{{ user_home_directory }}/deb/freecad_{{ freecad.version }}.AppImage"
    mode: 0774
- name: Make appimage executable
  file: "dest={{ user_home_directory }}/deb/freecad_{{ freecad.version }}.AppImage mode=a+x"
- name: Create desktop file
  template:
    src: "freecad.desktop.j2"
    dest: "{{ user_home_directory }}/.local/share/applications/freecad.desktop"