- name: Install apt packages
  apt:
    pkg:
      - libfuse2
    state: latest
    update_cache: true
- name: Find old versions
  find:
    paths: "{{ user_home_directory }}/deb"
    patterns: "seafile-client_*.AppImage"
  register: old_files
- name: Clean up old versions
  file:
    path: "{{ item['path'] }}"
    state: absent
  when: "item['path'] != user_home_directory + '/deb/seafile-client_' + seafile.version + '.AppImage'"
  with_items: "{{ old_files['files'] }}"
- name: Download AppImage
  get_url:
    url: "https://sos-ch-dk-2.exo.io/seafile-downloads/Seafile-x86_64-{{  seafile.version }}.AppImage"   
    dest: "{{ user_home_directory }}/deb/seafile-client_{{ seafile.version }}.AppImage"
    mode: 0774
- name: Make appimage executable
  file: "dest={{ user_home_directory }}/deb/seafile-client_{{ seafile.version }}.AppImage mode=a+x"
# Enable "Hide Main Window on start" to hide the GUI on startup.
- name: Template autostart
  template:
    src: "seafile.desktop.j2"
    dest: "{{ user_home_directory }}/.config/autostart/seafile.desktop"
- name: Template desktop file
  template:
    src: "seafile.desktop.j2"
    dest: "{{ user_home_directory }}/.local/share/applications/seafile.desktop"