- name: Install dependencies
  apt:
    pkg:
      - kitty # Terminal emulator
      - fzf # Fuzzy finder
    state: latest
    update_cache: true
- name: Install starship prompt
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
- name: Template starship configuration
  template:
    src: "starship.toml.j2"
    dest: "{{ user_home_directory }}/.config/starship.toml"
- name: Make kitty config folder
  file:
    state: directory
    path: "{{ user_home_directory }}/.config/kitty"
- name: Template kitty configuration
  template:
    src: "kitty.conf.j2"
    dest: "{{ user_home_directory }}/.config/kitty/kitty.conf"
  