# Check
- name: check if font is present
  command: fc-list "JetBrains Mono" -q
  ignore_errors: yes
# Remove leftovers from older versions
- name: Delete old fonts folder
  ansible.builtin.file:
    state: absent
    path: "{{ user_home_directory }}/.local/share/fonts"
- name: Remove apt installed font
  apt:
    pkg:
      - fonts-jetbrains-mono
    state: absent
# Download jetbrains-mono
- name: Make tmp folder
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "/tmp/ansible/fonts"
    - "/tmp/ansible/fonts/jetbrains-mono"
- name: Download font
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip"
    dest: "/tmp/ansible/fonts"
    mode: 0440
- name: Unpack font
  unarchive:
    src: "/tmp/ansible/fonts/JetBrainsMono.zip"
    dest: /tmp/ansible/fonts/jetbrains-mono
    copy: no
- name: Make font folder
  file:
    state: directory
    path: "/usr/share/fonts/truetype/jetbrains-mono"
- name: Copy fonts
  copy:
    src: /tmp/ansible/fonts/jetbrains-mono/
    dest: /usr/share/fonts/truetype/jetbrains-mono/
# Cleanup
- name: Remove tmp folder
  file:
    state: absent
    path: "/tmp/ansible/fonts"
# Refresh cache
- name: refresh font cache
  shell: fc-cache -f